name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v2.1.3

jobs:
  publish_dockerhub:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install GraphViz
        run: sudo apt-get install graphviz -y
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Build Java server
        run: make buildServer
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config: .github/buildkitd.toml
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Docker images
        run: RELEASE_VERSION=${GITHUB_REF#refs/*/v*} make publishDockerImages
